apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content
  labels:
    app: ghost
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: netapp-files
  resources:
    requests:
      storage: 5Gi
